export const catalog = {
  striking: [
    { key: "jab", ja: "ジャブ", en: "Jab" },
    { key: "cross", ja: "クロス", en: "Cross" },
    { key: "jab_cross", ja: "ワンツー", en: "Jab–Cross" },
    { key: "left_hook", ja: "レフトフック", en: "Left Hook" },
    { key: "check_hook", ja: "チェックフック", en: "Check Hook" },
    { key: "calf_kick", ja: "カーフキック", en: "Calf Kick" },
    { key: "inside_low_kick", ja: "インロー", en: "Inside Low Kick" },
    { key: "teep", ja: "ティープ", en: "Teep" },
    { key: "overhand_right", ja: "オーバーハンド", en: "Overhand Right" },
    { key: "clinch_elbow", ja: "クリンチエルボー", en: "Clinch Elbow" },
  ],
  wrestling: [
    { key: "double_leg", ja: "ダブルレッグ", en: "Double Leg" },
    { key: "single_leg", ja: "シングルレッグ", en: "Single Leg" },
    { key: "body_lock", ja: "ボディロック", en: "Body Lock" },
    { key: "level_change", ja: "レベルチェンジ", en: "Level Change" },
    { key: "ankle_pick", ja: "アンクルピック", en: "Ankle Pick" },
    { key: "snap_down", ja: "スナップダウン", en: "Snap Down" },
    { key: "sprawl", ja: "スプロール", en: "Sprawl" },
    { key: "trip_outside_reap", ja: "外掛け", en: "Outside Reap" },
    { key: "mat_return", ja: "マットリターン", en: "Mat Return" },
    { key: "cage_press", ja: "ケージプレッシャー", en: "Cage Press" },
  ],
  tactics: [
    { key: "gameplan_a", ja: "ゲームプランA", en: "Gameplan A" },
    { key: "pressure_wrestling_wall_work", ja: "ウォールワーク", en: "Pressure Wrestling / Wall Work" },
    { key: "feint_setup", ja: "フェイント", en: "Feint Setup" },
    { key: "distance_management", ja: "距離管理", en: "Distance Management" },
    { key: "counter_flow", ja: "カウンターフロー", en: "Counter Flow" },
    { key: "cage_circle_out", ja: "ケージ回避", en: "Cage Circle Out" },
    { key: "tempo_shift", ja: "テンポ変化", en: "Tempo Shift" },
    { key: "conserve_energy", ja: "省エネ", en: "Conserve Energy" },
    { key: "southpaw_drill", ja: "サウスポードリル", en: "Southpaw Drill" },
    { key: "study_video", ja: "動画学習", en: "Study Video" },
  ],
  grappling: {
    submissions: [
      { key: "rear_naked_choke", ja: "リアネイキッドチョーク", en: "Rear Naked Choke" },
      { key: "guillotine_choke", ja: "ギロチンチョーク", en: "Guillotine Choke" },
      { key: "triangle_choke", ja: "三角絞め", en: "Triangle Choke" },
      { key: "arm_triangle_choke", ja: "アームトライアングル", en: "Arm Triangle Choke" },
      { key: "d_arce_choke", ja: "ダースチョーク", en: "D'Arce Choke" },
      { key: "anaconda_choke", ja: "アナコンダチョーク", en: "Anaconda Choke" },
      { key: "north_south_choke", ja: "ノースサウスチョーク", en: "North-South Choke" },
      { key: "ezekiel_choke", ja: "エゼキエルチョーク", en: "Ezekiel Choke" },
      { key: "peruvian_necktie", ja: "ペルビアンネクタイ", en: "Peruvian Necktie" },
      { key: "von_flue_choke", ja: "ヴォンフルーチョーク", en: "Von Flue Choke" },
      { key: "armbar", ja: "腕十字固め", en: "Armbar" },
      { key: "kimura_lock", ja: "キムラロック", en: "Kimura" },
      { key: "americana_keylock", ja: "アメリカーナ", en: "Americana (Keylock)" },
      { key: "omoplata", ja: "オモプラッタ", en: "Omoplata" },
      { key: "straight_ankle_lock", ja: "アキレス腱固め", en: "Straight Ankle Lock" },
      { key: "heel_hook", ja: "ヒールフック", en: "Heel Hook" },
      { key: "kneebar", ja: "ニーバー", en: "Kneebar" },
      { key: "toe_hold", ja: "トーホールド", en: "Toe Hold" },
      { key: "calf_slicer", ja: "カーフスライサー", en: "Calf Slicer" },
      { key: "twister", ja: "ツイスター", en: "Twister" },
    ],
    positions_and_control: [
      { key: "closed_guard", ja: "クローズドガード", en: "Closed Guard" },
      { key: "open_guard", ja: "オープンガード", en: "Open Guard" },
      { key: "butterfly_guard", ja: "バタフライガード", en: "Butterfly Guard" },
      { key: "half_guard", ja: "ハーフガード", en: "Half Guard" },
      { key: "deep_half_guard", ja: "ディープハーフ", en: "Deep Half Guard" },
      { key: "knee_shield_guard", ja: "ニーシールド", en: "Knee Shield (Z Guard)" },
      { key: "de_la_riva_guard", ja: "デラヒーバ", en: "De La Riva Guard" },
      { key: "x_guard", ja: "Xガード", en: "X Guard" },
      { key: "single_leg_x_ashi_garami", ja: "シングルレッグX", en: "Single-Leg X (Ashi Garami)" },
      { key: "fifty_fifty_guard", ja: "50/50", en: "50/50 Guard" },
      { key: "rubber_guard", ja: "ラバーガード", en: "Rubber Guard" },
      { key: "side_control", ja: "サイドコントロール", en: "Side Control" },
      { key: "north_south_position", ja: "ノースサウス", en: "North–South Position" },
      { key: "mount", ja: "マウント", en: "Mount" },
      { key: "technical_mount", ja: "テクニカルマウント", en: "Technical Mount (S-Mount)" },
      { key: "knee_on_belly", ja: "ニーオンベリー", en: "Knee on Belly" },
      { key: "back_mount_hooks", ja: "バックマウント（フックス）", en: "Back Mount (Hooks)" },
      { key: "body_triangle_control", ja: "ボディトライアングル", en: "Body Triangle" },
      { key: "turtle_control", ja: "タートル", en: "Turtle Control" },
      { key: "kesa_gatame_scarf_hold", ja: "袈裟固め", en: "Kesa-Gatame (Scarf Hold)" },
    ],
    sweeps: [
      { key: "hip_bump_sweep", ja: "ヒップバンプ", en: "Hip Bump (Sit-up) Sweep" },
      { key: "scissor_sweep", ja: "シザースイープ", en: "Scissor Sweep" },
      { key: "pendulum_flower_sweep", ja: "フラワー/ペンデュラム", en: "Pendulum (Flower) Sweep" },
      { key: "butterfly_sweep", ja: "バタフライスイープ", en: "Butterfly Sweep" },
      { key: "tripod_sweep", ja: "トライポッド", en: "Tripod Sweep" },
      { key: "lumberjack_sweep", ja: "ランバージャック", en: "Lumberjack Sweep" },
      { key: "waiter_sweep", ja: "ウェイター", en: "Waiter Sweep" },
      { key: "old_school_sweep", ja: "オールドスクール", en: "Old School Sweep" },
      { key: "balloon_sweep", ja: "バルーンスイープ", en: "Balloon Sweep" },
      { key: "tornado_sweep", ja: "トルネードスイープ", en: "Tornado Sweep" },
    ],
    escapes: [
      { key: "upa_bridge_escape", ja: "ブリッジ&ロール（ウパ）", en: "Bridge & Roll (Upa) Escape" },
      { key: "elbow_knee_escape", ja: "エルボー・ニー（シュリンプ）", en: "Elbow–Knee (Shrimp) Escape" },
      { key: "knee_elbow_escape_side", ja: "サイドの肘膝エスケープ", en: "Side Elbow–Knee Escape" },
      { key: "back_escape_two_on_one", ja: "バックの2on1エスケープ", en: "Back Escape (2-on-1)" },
      { key: "north_south_escape", ja: "ノースサウスからのエスケープ", en: "North–South Escape" },
    ],
  },
};
